version: '3'

services:
  flask_app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:latest
    container_name: mysql_tune_fusion
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql@123
      MYSQL_DATABASE: tune_fusion_db
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 45s
      retries: 50

volumes:
  mysqldata:
